name: Flutter Build APK

on:
  push:
    branches:
      - main
      - offline
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # ** AÑADE ESTE BLOQUE: Decodifica y coloca el google-services.json **
      - name: Decode Google Services JSON
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      # SUGERENCIA: Añadir flutter clean para mayor robustez
      - name: Clean Flutter project
        run: | 
          flutter clean
          flutter pub cache repair

      - name: Install dependencies
        run: | 
          flutter pub get
          flutter pub upgrade

      # 🚨 NUEVO: Limpieza y generación de archivos automáticos (*.g.dart) para json_serializable sin flags obsoletas 🚨
      - name: Run Build Runner Clean
        run: flutter pub run build_runner clean

      - name: Run Build Runner Build
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK (Optimized)
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/app-*-release.apk
          retention-days: 2 # Se borra automáticamente en 48 horas
